nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/w3cj

projects_url: http://github.com/w3cj

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/w3cj
        instagram: https://www.instagram.com/makervanlife
        twitch: https://twitch.tv/w3cj
        youtube: https://www.youtube.com/c/CJReynolds-Galvanize
        meetup: https://www.meetup.com/members/39245842
        twitter: https://twitter.com/cjr2d2
    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: maker-van-life # Disqus Comments Shortname
    google_analytics: # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
